version: "2"

services:
  eureka-peer1:
    build:
      context: ./servicediscovery
    image: servicediscovery:1.0.0
    container_name: eureka1
    environment:
      - JAVA_OPTS=-Deureka.host=eureka1 -Deureka.port=8761 -Dreplica.url=http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
#      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8761:8761"
    networks:
      - network-poc

  eureka-peer2:
    build:
      context: ./servicediscovery
    image: servicediscovery:1.0.0
    container_name: eureka2
    environment:
      - JAVA_OPTS=-Deureka.host=eureka2 -Deureka.port=8762 -Dreplica.url=http://eureka1:8761/eureka/,http://eureka3:8763/eureka/
#      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8762:8762"
    networks:
      - network-poc
      
  eureka-peer3:
    build:
      context: ./servicediscovery
    image: servicediscovery:1.0.0
    container_name: eureka3
    environment:
      - JAVA_OPTS=-Deureka.host=eureka3 -Deureka.port=8763 -Dreplica.url=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
#      - LOGGING_LEVEL_COM_NETFLIX_DISCOVERY=DEBUG
    ports:
      - "8763:8763"
    networks:
      - network-poc      

  microservices-1:
    build:
      context: ./microservices
    image: microservices:1.0.0
    container_name: microservices
    environment:
      - JAVA_OPTS=-Dport=2267 -Dregistry.url=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
#    ports:
#      - "2267:2267" Access will be through gateway only.
    networks:
      - network-poc
      
  microservices-2:
    build:
      context: ./microservices2
    image: microservices2:1.0.0
    container_name: microservices2
    environment:
      - JAVA_OPTS=-Dport=2268 -Dregistry.url=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
#    ports:
#      - "2268:2268" This is internally used by microservices-1, so we dont want to expose it outside container. Anyways access is through gateway only
    networks:
      - network-poc

  api-gateway-zuul:
    build:
      context: ./apiGWay-zuul
    image: api-gateway-zuul:1.0.0
    container_name: apiGWay-zuul
    environment:
      - JAVA_OPTS=-Dport=7777 -Dregistry.url=http://eureka1:8761/eureka/,http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    ports:
      - "80:7777"
    networks:
      - network-poc

      
networks:
  network-poc: