spring:
  application:
    name: microservices-2
    
server:
  port: ${PORT:2268}

eureka:
  client:
    serviceUrl:
      defaultZone: http://rvi:8763/eureka/,http://rv2:8764/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
