spring:
  application:
    name: microservices-2
    
server:
  port: ${port:2268}

eureka:
  client:
    serviceUrl:
      defaultZone: ${registry.url:http://localhost:8761/eureka/}
#  instance:
#    instanceId: ${spring.application.name}:${server.port}
#    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}