spring:
  application:
    name: zuul-api-gateway
server:
  port: ${zuul.port:7777}

eureka:
  client: 
    serviceUrl:
      defaultZone: ${registry.url:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true      
  instance:
    preferIpAddress: true
              
zuul:
  routes:
    microservices-1:
      path: /rb/** #optional - this is here for illustration only that microservice-1 can also be accessed using URI /rb

management:
  endpoints:
    web:
      exposure:
        include: '*'

ribbon:
  ReadTimeout: 30000
  SocketTimeout: 30000

  